### ISSUE TITLE
Error: invalid argument at Connection

### ISSUE THREAD

**Issue by guest271314** [saghul/txiki.js#523]
I'm writing a JavaScript runtime agnostic HTTP and WebSocket server.

txiki.js `Connection` throws  

```
Error: invalid argument
    at pull (:0:0)
    at apply (native)
    at call (native)
    at x (:0:0)
    at C (:0:0)
    at <anonymous> (:0:0)
    at <anonymous> (:0:0)
    at Ht (:0:0)
    at [[[PullSteps]]] (:0:0)
    at Rr (:0:0)

Trace: 
    at <anonymous> (txikijs-ws-server.js:86:3)
```
when sending WebSocket close frame to the client.

I don't know where or why the error is thrown.

Essentially the same code does not throw when Direct Sockets `TCPServerSocker` is used as a WebSocket server in an Isolated Web App in Chromium and Chrome browsers.

Steps to reproduce:

Download attached files to the same directory, run the following 

```
 tjs run txikijs-ws-server.js
```

For client run

```
deno run -A --unstable websocketstream.js
```

or run the same code in Chromium or Chrome browser which supports WebSocketStream.

Relevant code in txikijs-ws-server.js L36-52

```
if (!/(GET|POST|HEAD|OPTIONS|QUERY)/i.test(request)) {
  // console.log({ data });
  const response = parseWebSocketFrame(data);
  console.log({
    response
  });
  if (response === null) {
    // https://stackoverflow.com/a/17177146
    const closeFrame = new Uint8Array([0x88, 0x00]); // 136, 0
    console.log(closeFrame);
    await writer.ready;
    await writer.write(closeFrame);
    await writer.close();
    await writer.closed.then(() => console.log("writer closed"));
    return;
    // return abortable.abort("WebSocket closed by client, aborted in server");
  } else {
    await writer.write(new Uint8Array(response));
  }
```

and the end of `writable` side of `Connecion` piped to a `WritableStream()` where the error is read L73-88.

```
        close() {
          console.log("Stream closed");
        },
        abort(reason) {
          console.log(reason);
        },
      })
    , {highWaterMark: Infinity})
    .then(() => console.log("Stream aborted")).catch((e) => {
      throw e;
    });
} catch (e) {
  //console.log(e.stack);
  console.trace();
  listener.close();
}
```

Tested with `deno` version 1.43.3 (release, x86_64-unknown-linux-gnu) and Chromium Version 126.0.6477.0 (Developer Build) (64-bit).

txiki.js version: v23.12.0.

Potentially related: https://github.com/saghul/txiki.js/issues/450.

**Comment by guest271314** [comment]
[tjs-ws-streams-throw.zip](https://github.com/saghul/txiki.js/files/15367314/tjs-ws-streams-throw.zip)

**Comment by saghul** [comment]
Can you try making a debug from latest master? The backtrace will be more meaningfull. You can do that with `make debug`

**Comment by guest271314** [comment]
I don't see much difference in the output in terminal with a debug build

```
tjs run txikijs-ws-server.js
Listening on family: 2, ip: 0.0.0.0, port: 8080
{ family: 2, ip: '127.0.0.1', port: 8080 } { family: 2, ip: '127.0.0.1', port: 59444 }
{ response: {} }
[connection close frame]

Close frame null
{ response: null }
{ '0': 136, '1': 0 }
writer closed
Error: invalid argument
    at pull (�W$:0:0)
    at apply (native)
    at call (native)
    at x (�W$:0:0)
    at C (�W$:0:0)
    at <anonymous> (�W$:0:0)
    at <anonymous> (�W$:0:0)
    at Ht (�W$:0:0)
    at [[[PullSteps]]] (�W$:0:0)
    at Rr (�W$:0:0)

Trace: 
    at <anonymous> (txikijs-ws-server.js:86:3)

```

**Comment by guest271314** [comment]
@saghul This is still broken. 

This should work. It just exits.

```
// https://github.com/saghul/txiki.js/blob/8460eaedd13225dc2ea6761a8cca7bfd2f06f6b0/tests/test-tcp.js
// https://github.com/saghul/txiki.js/blob/8460eaedd13225dc2ea6761a8cca7bfd2f06f6b0/tests/test-web-streams.js

import { WebSocketConnection } from "./websocket-server.js";

const decoder = new TextDecoder();

const listener = await tjs.listen("tcp", "127.0.0.1", "8080");
const { family, ip, port } = listener.localAddress;
console.log(`Listening on family: ${family}, ip: ${ip}, port: ${port}`);

try {
  const conn = await listener.accept();
  const writer = conn.writable.getWriter();

  await conn.readable
    .pipeTo(
      new WritableStream({
        start(controller) {
          this.ws = void 0;
          const { readable: wsReadable, writable: wsWritable } =
              new TransformStream(),
            wsWriter = wsWritable.getWriter();
          Object.assign(this, { wsReadable, wsWritable, wsWriter });
        },
        async write(value, controller) {
          const request = decoder.decode(value);
          if (request.includes("Upgrade: websocket")) {
            const [key] = request.match(/(?<=Sec-WebSocket-Key: ).+/i);
            const handshake = await WebSocketConnection.hashWebSocketKey(
              key,
              writer,
            );
            this.ws = new WebSocketConnection(this.wsReadable, writer)
              .processWebSocketStream().catch((e) => {
                throw e;
              });
          } else {
            await this.wsWriter.ready;
            await this.wsWriter.write(value);
          }
        },
        close() {
          console.log("Stream closed");
        },
        abort(reason) {
          console.log({
            reason,
          });
        },
      }),
    ).catch((e) => {
      throw e;
    });
} catch (e) {
  listener.close();
}

```

**Comment by guest271314** [comment]
Might be use of `crypto.subtle`.

**Comment by saghul** [comment]
Yes crypto.subtle is not currently implemented.

**Comment by guest271314** [comment]
That's not it. I used a has polyfil and `tjs` is still exiting when I try to do the WebSocket handshake.

**Comment by guest271314** [comment]
The current iteration of the code looks something like this

```
#!/usr/bin/env -S /home/user/bin/tjs run
// https://github.com/saghul/txiki.js/blob/8460eaedd13225dc2ea6761a8cca7bfd2f06f6b0/tests/test-tcp.js
// https://github.com/saghul/txiki.js/blob/8460eaedd13225dc2ea6761a8cca7bfd2f06f6b0/tests/test-web-streams.js
import { WebSocketConnection } from "./websocket-server.js";

const decoder = new TextDecoder();

const listener = await tjs.listen("tcp", "127.0.0.1", "8080");
const { family, ip, port } = listener.localAddress;
console.log(`Listening on family: ${family}, ip: ${ip}, port: ${port}`);

try {
  const conn = await listener.accept();
  const writer = conn.writable.getWriter();

  await conn.readable
    .pipeTo(
      new WritableStream({
        start(controller) {
          this.ws = void 0;
         // const { readable: wsReadable, writable: wsWritable } =
          //    new TransformStream(),
          //  wsWriter = wsWritable.getWriter();
         // Object.assign(this, { wsReadable, wsWritable, wsWriter });
        },
        async write(value, controller) {
          const request = decoder.decode(value);
          if (request.includes("Upgrade: websocket")) {
            const [key] = request.match(/(?<=Sec-WebSocket-Key: ).+/i);
            const handshake = await WebSocketConnection.hashWebSocketKey(
              key,
              writer,
            );
/*
            this.ws = new WebSocketConnection(this.wsReadable, writer)
              .processWebSocketStream().catch((e) => {
                throw e;
              });
*/
          } else {
           // await this.wsWriter.ready;
           // await this.wsWriter.write(value);
            console.log(value);
          }
        },
        close() {
          console.log("Stream closed");
        },
        abort(reason) {
          console.log({
            reason,
          });
        },
      }),
    ).catch((e) => {
      throw e;
    });
} catch (e) {
  listener.close();
}
```

This is the JavaScript runtime agnostic WebSocket server https://gist.github.com/guest271314/d330c7cea513f12ef7bf523c56431453.

For `tjs` I substituted `crypto.subtle` for

```
const resp = btoa(
      String.fromCodePoint.apply(
        null,
        createHash().update(new TextEncoder().encode(key)).digest(),
      ),
    );
```

**Comment by guest271314** [comment]
Appears that way. I don't think this https://github.com/saghul/txiki.js/issues/450 was fixed, yet.

**Comment by saghul** [comment]
They do work, the bug is is the fetch polyfill.

**Comment by guest271314** [comment]
@saghul I tried a few hundred times to get the WebSocket server working using txiki.js WHATWG Streams implementation, to no avail.

I did manage to get the code working as expected writing to `Connection` interface directly, without using the `WritableStream` polyfill.

For `tjs` in the server, or for cases where there's no `WritableStreamDefaultWriter` or `WritableStream`, and where there's no Web Cryptography API `crypto.subtle` https://gist.github.com/guest271314/d330c7cea513f12ef7bf523c56431453#file-websocket-server-js-L214-L235

```
    } else {
      const encoder = new TextEncoder();
      const hash = createHash().update(
        encoder.encode(
          `${secKeyWebSocket}${WebSocketConnection.KEY_SUFFIX}`,
        ),
      ).digest();
      const key = btoa(
        String.fromCodePoint.apply(
          null,
          [...hash],
        ),
      );
      const header = "HTTP/1.1 101 Web Socket Protocol Handshake\r\n" +
        "Upgrade: WebSocket\r\n" +
        "Connection: Upgrade\r\n" +
        "sec-websocket-accept: " + key + "\r\n\r\n";
      const encoded = encoder.encode(header);
      return writable instanceof WritableStream
        ? new Response(encode).body.pipeTo(writable, { preventClose: !0 })
        : writable.write(encoded);
    }
```

`tjs run tjs-ws.js`

```
import { WebSocketConnection } from "./websocket-server.js";

const encoder = new TextEncoder();
const decoder = new TextDecoder();
// https://github.com/saghul/txiki.js/blob/master/examples/echo-server.js
async function handleConnection(conn) {
  console.log(conn.localAddress, conn.remoteAddress);
  const readable = conn.readable;
  const { readable: wsReadable, writable: wsWritable } = new TransformStream(),
    wsWriter = wsWritable.getWriter();
  let ws;
  for await (const value of conn.readable) {
    const request = decoder.decode(value);
    if (request.includes("Upgrade: websocket")) {
      const [key] = request.match(/(?<=Sec-WebSocket-Key: ).+/i);
      const handshake = await WebSocketConnection.hashWebSocketKey(
        key,
        conn,
      );
      ws = new WebSocketConnection(wsReadable, conn)
        .processWebSocketStream().catch((e) => {
          throw e;
        });
    } else {
      await wsWriter.ready;
      await wsWriter.write(new Uint8Array(value));
    }
  }
  console.log("Socket closed");
}

const l = await tjs.listen("tcp", "0.0.0.0", "8080");

const { family, ip, port } = l.localAddress;
console.log(`Listening on family: ${family}, ip: ${ip}, port: ${port}`);

for await (let conn of l) {
  await handleConnection(conn);
  conn = undefined;
}
```


![Image](https://github.com/user-attachments/assets/588cc70f-e0c0-4dfb-be6e-85ded0fff6e7)

![Image](https://github.com/user-attachments/assets/e97d6727-1fb0-4bac-9d5e-609b390ea0a8)
